---
# tasks file for roles/web
- name: Install NGINX
  apt:
    name: nginx
    update_cache: true


- name: Install Git
  apt: 
    name: git
    state: present
    update_cache: true


- name: Git clone
  git:
    repo: "https://github.com/Rakantonio/tp-final-pipeline-2 /var/www/html/"
